import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';
import { saveAs } from 'file-saver';

const WATERMARK_TEXT = 'DRAFT — Generated by Lawie (Free Tier)';

/**
 * Export the editor HTML content as a PDF file.
 * Uses html2pdf.js (client-side, no puppeteer needed).
 */
export async function exportPdf(html: string, title: string, isFree: boolean): Promise<void> {
  // Dynamic import — html2pdf.js is a large bundle, only load when needed
  const html2pdf = (await import('html2pdf.js')).default;

  const wrapper = document.createElement('div');
  wrapper.innerHTML = html;
  wrapper.style.fontFamily = 'serif';
  wrapper.style.fontSize = '12pt';
  wrapper.style.lineHeight = '1.6';
  wrapper.style.padding = '40px';
  wrapper.style.maxWidth = '210mm';

  if (isFree) {
    const watermark = document.createElement('div');
    watermark.textContent = WATERMARK_TEXT;
    watermark.style.cssText =
      'position:fixed;top:50%;left:50%;transform:translate(-50%,-50%) rotate(-45deg);font-size:48px;color:rgba(0,0,0,0.06);pointer-events:none;z-index:9999;white-space:nowrap;';
    wrapper.appendChild(watermark);
  }

  const filename = `${title.replace(/[^a-zA-Z0-9\s-]/g, '').slice(0, 60)}.pdf`;

  await html2pdf()
    .set({
      margin: [15, 15, 15, 15],
      filename,
      image: { type: 'jpeg', quality: 0.95 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
    })
    .from(wrapper)
    .save();
}

/**
 * Parse simple HTML into docx paragraphs.
 * Handles: <h1-h3>, <p>, <strong>, <em>, <u>, <br>, <li>.
 */
function htmlToDocxParagraphs(html: string, isFree: boolean): Paragraph[] {
  const paragraphs: Paragraph[] = [];
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, 'text/html');

  function processNode(node: Node): TextRun[] {
    const runs: TextRun[] = [];
    if (node.nodeType === Node.TEXT_NODE) {
      const text = node.textContent ?? '';
      if (text) runs.push(new TextRun(text));
    } else if (node.nodeType === Node.ELEMENT_NODE) {
      const el = node as HTMLElement;
      const tag = el.tagName.toLowerCase();

      if (tag === 'br') {
        runs.push(new TextRun({ break: 1 }));
        return runs;
      }

      const childRuns: TextRun[] = [];
      el.childNodes.forEach((child) => childRuns.push(...processNode(child)));

      for (const run of childRuns) {
        const opts: Record<string, unknown> = {};
        if (tag === 'strong' || tag === 'b') opts.bold = true;
        if (tag === 'em' || tag === 'i') opts.italics = true;
        if (tag === 'u') opts.underline = {};

        if (Object.keys(opts).length > 0) {
          runs.push(
            new TextRun({
              text: (run as TextRun & { text?: string }).text ?? '',
              ...opts,
            }),
          );
        } else {
          runs.push(run);
        }
      }
    }
    return runs;
  }

  const body = doc.body;
  body.childNodes.forEach((node) => {
    if (node.nodeType !== Node.ELEMENT_NODE) return;
    const el = node as HTMLElement;
    const tag = el.tagName.toLowerCase();

    let heading: (typeof HeadingLevel)[keyof typeof HeadingLevel] | undefined;
    if (tag === 'h1') heading = HeadingLevel.HEADING_1;
    else if (tag === 'h2') heading = HeadingLevel.HEADING_2;
    else if (tag === 'h3') heading = HeadingLevel.HEADING_3;

    const align = el.style.textAlign;
    let alignment: (typeof AlignmentType)[keyof typeof AlignmentType] | undefined;
    if (align === 'center') alignment = AlignmentType.CENTER;
    else if (align === 'right') alignment = AlignmentType.RIGHT;
    else if (align === 'justify') alignment = AlignmentType.JUSTIFIED;

    if (tag === 'ul' || tag === 'ol') {
      el.querySelectorAll('li').forEach((li) => {
        paragraphs.push(
          new Paragraph({
            children: processNode(li),
            bullet: tag === 'ul' ? { level: 0 } : undefined,
            numbering: tag === 'ol' ? { reference: 'default-numbering', level: 0 } : undefined,
          }),
        );
      });
    } else {
      paragraphs.push(
        new Paragraph({
          children: processNode(el),
          heading,
          alignment,
        }),
      );
    }
  });

  if (isFree) {
    paragraphs.push(new Paragraph({ children: [] }));
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({
            text: WATERMARK_TEXT,
            color: 'CCCCCC',
            size: 18,
            italics: true,
          }),
        ],
        alignment: AlignmentType.CENTER,
      }),
    );
  }

  return paragraphs;
}

/**
 * Export the editor HTML content as a DOCX file.
 * Uses the `docx` package (client-side generation).
 */
export async function exportDocx(html: string, title: string, isFree: boolean): Promise<void> {
  const paragraphs = htmlToDocxParagraphs(html, isFree);

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 2160, right: 1440 }, // 1.5" left (court standard)
          },
        },
        children: paragraphs,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  const filename = `${title.replace(/[^a-zA-Z0-9\s-]/g, '').slice(0, 60)}.docx`;
  saveAs(blob, filename);
}
